---
kind: pipeline
type: exec
os: linux
arch: amd64

name: CD

steps:
- name: stop containers
  commands:
    - docker-compose down
  failure: ignore
- name: update images
  commands:
    - docker-compose pull
- name: deploy containers
  commands:
    - docker-compose up -d --build
  environment:
    BOT_KEY:
      from_secret: BOT_KEY
    BUILD: 'PROD'
trigger:
  branch:
    - main
---
kind: signature
hmac: b00623ac1e27ebe7afa45fb7eff70e5fb984a444011121c030937bad5e6ffc3b

...
