---
kind: pipeline
type: exec
os: linux
arch: amd64

name: CD

steps:
- name: remove old deployed version
  failure: ignore
  commands:
    - docker stop giftDetester
    - docker rm giftDetester
    - docker rmi gift-detester
- name: deploy new docker image
  commands:
    - docker build -t gift-detester .
    - docker run -d --name giftDetester -e BOT_KEY gift-detester
  environment:
    BOT_KEY:
      from_secret: BOT_KEY
trigger:
  branch:
    - master
---
kind: signature
hmac: 8670cefb3bcf874ee90c163741477127348a6b57c88f2087fae80600bd0e327d

...
